/**
 * The Arabic and Italian copy for every editable block.
 *
 * GENERATED by scripts/compile-block-translations.mjs from db/seed/blocks.*.tsv.
 * Edit the TSVs and re-run; do not edit this file by hand.
 *
 * It exists because the translations were written, committed, and then never
 * loaded: the seeding script was in no build step, content_blocks was empty in
 * production, and getBlocks() fell through to the English compiled into
 * content.ts. Arabic and Italian visitors read an English homepage.
 *
 * Compiled rather than seeded on deploy, for the same reason the English
 * fallback is compiled: the production image is built with no database, so
 * anything that depends on a row existing is a page that can ship empty. The
 * database still wins where it has a value — this is the floor, not the
 * ceiling.
 */
import type { Locale } from '@/lib/i18n';

export const BLOCK_TRANSLATIONS: Partial<Record<Locale, Record<string, string>>> = {
  "ar": {
    "home.hero.eyebrow": "أشجار إيطالية فاخرة · توريد في جميع أنحاء الإمارات",
    "home.hero.title": "زيتون إيطالي معمّر.",
    "home.hero.title.em": "مغروس في الإمارات.",
    "home.hero.lede": "أشجار زيتون مميّزة ونخيل ونباتات معمارية — تُنتقى من المشتل في {regions}، وتُستورد وتُؤقلم، ثم تُسلَّم إلى الموقع في جميع أنحاء الإمارات.",
    "home.hero.cta": "تصفّح أشجارنا",
    "home.hero.cta.two": "اطلب عرض سعر",
    "home.badge.top": "أصيلة",
    "home.badge.mid": "إيطالية",
    "home.badge.low": "أشجار",
    "home.feature.1": "مستوردة من إيطاليا",
    "home.feature.2": "تشكيلة واسعة من الأشجار الفاخرة",
    "home.feature.3": "توصيل في جميع أنحاء الإمارات",
    "home.feature.4": "دعم فني ومتابعة بعد الغرس",
    "home.featured.eyebrow": "مجموعة مختارة",
    "home.featured.note": "جمالٌ لا يشيخ، وجذورٌ في التاريخ.",
    "home.route.eyebrow": "من أين تأتي",
    "home.route.title": "أربع مناطق إيطالية.",
    "home.route.title.two": "سبع إمارات.",
    "home.route.note": "نشتري من المزارع مباشرةً، لا من وسيط. وكل شحنة تُفحص، وتُوثَّق للاستيراد، وتُؤقلم هنا قبل أن تصل إلى أي موقع.",
    "home.band.eyebrow": "لماذا نُسعّر بعرض سعر",
    "home.band.quote": "شجرة زيتون بارتفاع ثلاثة أمتار ليست سلعة تُشترى من سلّة تسوّق.",
    "home.band.body": "شجرتان بالارتفاع الاسمي نفسه تختلفان تمامًا في محيط الجذع والتاج والطابع — وبالتالي في السعر. أضف إلى ذلك الشحن والموسم والكمية وإمكانية الوصول إلى الموقع، وسيتبيّن أن أي سعر ثابت على الإنترنت هو وهم.",
    "home.band.cta": "ابدأ استفسارك",
    "home.who.title": "مصمَّمة للمشاريع.",
    "home.coverage.title": "الإمارات السبع جميعها.",
    "faq.title": "أسئلة تُطرح علينا",
    "faq.intro": "ما يسأل عنه المشترون قبل أن يرسلوا استفسارهم. وإن لم يكن سؤالك هنا، اطرحه في نموذج الاستفسار وستصلك الإجابة مباشرةً.",
    "testimonials.title": "ماذا يقول عملاؤنا",
    "journal.title": "المدوّنة",
    "journal.intro": "ملاحظات في اختيار أشجار البحر المتوسط واستيرادها وترسيخها في الخليج — مكتوبة لمن سيعيش مع النتيجة."
  },
  "it": {
    "home.hero.eyebrow": "Alberi italiani di pregio · Fornitura in tutti gli Emirati",
    "home.hero.title": "Olivi secolari italiani.",
    "home.hero.title.em": "Piantati negli Emirati.",
    "home.hero.lede": "Olivi esemplari, palme e piante architettoniche — selezionati in vivaio in {regions}, importati, acclimatati e consegnati in cantiere in tutti gli Emirati.",
    "home.hero.cta": "Scopri i nostri alberi",
    "home.hero.cta.two": "Richiedi un preventivo",
    "home.badge.top": "Autentici",
    "home.badge.mid": "Italiani",
    "home.badge.low": "Alberi",
    "home.feature.1": "Importati dall'Italia",
    "home.feature.2": "Ampia scelta di alberi di pregio",
    "home.feature.3": "Consegna in tutti gli Emirati",
    "home.feature.4": "Assistenza tecnica e cura nel tempo",
    "home.featured.eyebrow": "Collezione in evidenza",
    "home.featured.note": "Una bellezza senza tempo, radicata nella storia.",
    "home.route.eyebrow": "Da dove arrivano",
    "home.route.title": "Quattro regioni italiane.",
    "home.route.title.two": "Sette emirati.",
    "home.route.note": "Compriamo dal produttore, non da un intermediario. Ogni partita viene ispezionata, documentata per l'importazione e acclimatata qui prima di arrivare in cantiere.",
    "home.band.eyebrow": "Perché lavoriamo a preventivo",
    "home.band.quote": "Un olivo di tre metri non si mette in un carrello.",
    "home.band.body": "Due alberi della stessa altezza nominale sono completamente diversi per circonferenza del tronco, chioma e carattere — e quindi per prezzo. Ci si aggiungano trasporto, stagione, quantità e accessibilità del cantiere: un prezzo fisso online sarebbe una finzione.",
    "home.band.cta": "Invia una richiesta",
    "home.who.title": "Pensati per i progetti.",
    "home.coverage.title": "Tutti e sette gli Emirati.",
    "faq.title": "Le domande che ci fanno",
    "faq.intro": "Quello che i clienti chiedono prima di scriverci. Se la tua domanda non è qui, falla nel modulo di richiesta e riceverai una risposta diretta.",
    "testimonials.title": "Cosa dicono i clienti",
    "journal.title": "Giornale",
    "journal.intro": "Appunti sulla scelta, l'importazione e l'attecchimento degli alberi mediterranei nel Golfo — scritti per chi con il risultato dovrà conviverci."
  }
};
