import { DEFAULT_LOCALE, type Locale } from '@/lib/i18n';
import { COPY_DICTS, type CopyKey } from '@/lib/site-copy';

/**
 * The words the interface is made of, as opposed to the words the business
 * writes.
 *
 * These are deliberately NOT in content_blocks and not editable from the
 * console. The distinction is who owns the text:
 *
 *   The headline, the promise, the reason there is no checkout — the company
 *   rewrites those, so they live in the database and the console edits them,
 *   and an untranslated one falls back to English rather than blocking.
 *
 *   "Catalogue", "Close", "Request a quote" — nobody needs to rewrite those
 *   from a CMS, and making them editable would add three hundred fields to a
 *   screen that has thirty and is already long. They live here.
 *
 * And because they live here, a missing translation is a TYPE ERROR rather
 * than a fallback. `Record<UIKey, string>` means the build fails if Arabic is
 * missing a key. That is the right trade for chrome: an untranslated
 * paragraph reads as work in progress, while an English "Close" button on an
 * otherwise Arabic page reads as a bug — and there are only forty of them, so
 * finishing is not a project.
 */

const en = {
  // ── navigation ──
  'nav.catalog': 'Catalogue',
  'nav.collections': 'Collections',
  'nav.services': 'Services',
  'nav.journal': 'Journal',
  'nav.about': 'About',
  'nav.contact': 'Contact',
  'nav.main': 'Main',
  'nav.menu': 'Menu',
  'nav.open': 'Open the menu',
  'nav.closeMenu': 'Close the menu',
  'nav.close': 'Close',
  'nav.skip': 'Skip to content',

  // ── actions ──
  'cta.quote': 'Request a quote',
  'cta.quote.short': 'Quote',
  'cta.bulk': 'Bulk & project pricing',
  'cta.sourcing': 'Source a specific tree',
  'cta.viewAll': 'View the whole catalogue',

  // ── footer ──
  'ftr.catalogue': 'Catalogue',
  'ftr.company': 'Company',
  'ftr.enquiries': 'Enquiries',
  'ftr.aboutUs': 'About us',
  'ftr.legal': 'Legal',
  'ftr.allSpecimens': 'All {n} specimens',
  'ftr.deliveringTo': 'Delivering to',
  'ftr.sourcedFrom': 'Sourced from',
  'ftr.leadTime': 'Lead time',
  'ftr.weeksToSite': '{min}–{max} weeks to site',
  // The only key whose translations carry no {n}. English spells the number
  // ("All seven emirates"); Arabic and Italian inflect it with the noun, and a
  // token cannot be dropped into an inflected phrase without producing
  // something no native reader would write. They say "all the emirates"
  // instead, which cannot drift if the list ever changes — and the count
  // itself is guarded by tests/footer.test.mjs, which is where it belongs.
  'ftr.allEmirates': 'All {n} emirates',
  'ftr.rights': 'All prices on request.',
  'ftr.vat': 'Prices exclusive of VAT where applicable. Specifications are indicative; living stock varies in size and form.',
  'ftr.licence': 'Trade licence {n}',
  'ftr.trn': 'TRN {n}',

  // ── legal pages ──
  'legal.privacy': 'Privacy',
  'legal.terms': 'Terms of use',
  'legal.termsOfSale': 'Terms of sale',
  'legal.refunds': 'Replacements & refunds',
  'legal.disclaimer': 'Disclaimer',
  'legal.onThisPage': 'On this page',
  'legal.updated': 'Last updated {date}',
  'legal.email': 'Email:',
  'legal.telephone': 'Telephone:',
  'legal.enquiryForm': 'enquiry form',
  'legal.eyebrow': 'Legal',
  'legal.indexTitle': 'Legal',
  'legal.indexDescription': 'Privacy policy, terms of use, terms of sale, replacements and refunds, and the website disclaimer for Verde Garden Trading.',
  'legal.alsoOnThisSite': 'Also on this site:',
  'legal.registeredIn': 'registered in {city}, {country}.',
  'legal.licence': 'Trade licence:',
  'legal.trn': 'Tax registration number:',
  'legal.whatsapp': 'WhatsApp:',
  'legal.noChannelsA': 'Our published telephone number and mailbox go live with the company domain. Until they do, the',
  'legal.noChannelsB': 'is the way to reach us, and every enquiry sent through it is read — including one about this document. We would rather tell you that than print an address nobody is answering.',
  'legal.vatCharged': 'Prices are exclusive of VAT, which is added at {rate}% where it applies.',
  'legal.vatNotRegistered': 'Prices are exclusive of VAT. We are not currently VAT-registered, so no VAT is charged and none is shown — a supplier who is not registered may not charge it.',
  // Required by the decision to publish translated legal text at all. The
  // English is the version that was written and reviewed; a translation is
  // provided so it can be READ, and says so rather than implying otherwise.
  'legal.prevails': 'This page is a translation provided for convenience. In the event of any discrepancy, the English version prevails.',

  // ── catalogue ──
  'cat.sortReference': 'Reference',
  'cat.sortTallest': 'Tallest first',
  'cat.sortSmallest': 'Smallest first',
  'svc.s1.t': 'Selection at the grower',
  'svc.s1.b': 'We choose the individual plant in the nursery, in Toscana, Puglia, Sicilia or Lombardia — to your specification, not from whatever a stock list happens to hold that month.',
  'svc.s1.d': 'Photographs of the actual specimen before anything is committed.',
  'svc.s2.t': 'Import & documentation',
  'svc.s2.b': 'Phytosanitary certification, import permits, customs clearance and the paperwork that live plant material attracts at both ends.',
  'svc.s2.d': 'Handled by us. Nothing on this list becomes your problem at the border.',
  'svc.s3.t': 'Acclimatisation',
  'svc.s3.b': 'Conditioning on arrival before stock is released to site, so a tree that has just come out of an Italian winter meets a Gulf summer in stages.',
  'svc.s3.d': 'This is the step that decides whether a specimen establishes or fails in year one.',
  'svc.s4.t': 'Transport & offloading',
  'svc.s4.b': 'Low-loader, and crane or hiab where the root ball demands it. Site access — gate widths, overhead lines, ground bearing — is confirmed before a delivery date is agreed.',
  'svc.s4.d': 'Optional. Plenty of contractors take supply only, and that is quoted too.',
  'svc.s5.t': 'Planting',
  'svc.s5.b': 'Pit preparation, soil amendment, staking and irrigation connection, where planting is within the quoted scope.',
  'svc.s5.d': 'For schemes that run over months rather than a single delivery.',
  'svc.s6.t': 'Project supply',
  'svc.s6.b': 'Phased consignments held to one specification across a development, so the trees in phase four match the ones in phase one.',
  'svc.s6.d': 'One specification, held open for the life of the scheme.',
  'qf.type.quote': 'Quote a specimen',
  'qf.type.quote.hint': 'You know what you want',
  'qf.type.bulk': 'Bulk / project pricing',
  'qf.type.bulk.hint': 'Volume for a project',
  'qf.type.sourcing': 'Source a specific tree',
  'qf.type.sourcing.hint': 'Not in the catalogue',
  'qf.msg.sourcing': 'Describe the tree you are looking for — species, age, height, trunk girth, form',
  'qf.msg.general': 'Anything else we should know — site access, planting, timeline',
  'Add to your shortlist': 'Add to your shortlist',
  'Remove from your shortlist': 'Remove from your shortlist',
  'qf.contact.whatsapp': 'Send it to us on WhatsApp instead: {n}',
  'qf.contact.email': 'Email it to us instead: {n}',
  'qf.contact.retry': 'Please try again in a moment.',
  'qf.err.tooLong': 'That is longer than the form accepts. Shorten it and send it again.',
  'qf.err.name': 'Please give a name we can reply to.',
  'qf.err.email': 'That email address does not look right. Check it and send it again.',
  'qf.err.quantity': 'Quantity has to be a whole number of one or more.',
  'qf.err.consent': 'Please tick the box so we may reply to you.',
  'qf.err.generic': 'Something in the form was not accepted. Check the fields and send it again.',
  'qf.err.rateLimit': 'That is several enquiries in a short time. Wait a minute and try again.',
  'qf.err.notRecorded': 'Your enquiry was not recorded.',
  'cat.height': 'Height',
  'cat.addToList': 'Add to list',
  'cat.onList': 'On your list',
  'cat.shortlist': 'Your list',
  'cat.newPhoto': 'New photograph coming',
  'cat.priceOnRequest': 'Price on request',
  'seo.catalogTitle': 'Catalogue — Italian trees & plants for the UAE',
  'seo.catalogDesc': 'Browse specimen olive trees, palms, agaves, cacti and ornamental trees imported from Italy and supplied across the United Arab Emirates. All prices on request.',
  'seo.servicesTitle': 'Services — supply, import, delivery and planting',
  'seo.servicesDesc': 'Tree supply from Italian nurseries, import and phytosanitary documentation, acclimatisation, delivery with crane offloading, and planting across the UAE.',
  'seo.aboutTitle': 'About',
  'seo.aboutDesc': 'Verde Garden Trading imports premium trees and plants from Italian nurseries and supplies landscaping contractors, developers, hotels and private estates across the UAE.',
  'seo.contactTitle': 'Contact',
  'seo.contactDesc': 'Reach Verde Garden Trading — WhatsApp, phone and email, delivery across the United Arab Emirates, and what to send us so a quotation comes back the same day.',
  'seo.quoteTitle': 'Request a quote',
  'seo.quoteDesc': 'Tell us the species, sizes, quantities and site. We come back with availability, lead time and a priced quotation for delivery anywhere in the UAE.',
  'seo.locationTitle': 'Italian tree supply & delivery in {name}',
  'seo.locationDesc': '{intro} Specimen olive trees, palms and ornamental plants imported from Italy and delivered in {name}.',
  'seo.specimenTitle': '{name}{size} — imported from Italy',
  'seo.specimenDesc': '{desc} Reference {ref}. Supplied and delivered across the UAE. Price on request.',
  'seo.collectionTitle': '{name} imported from Italy to the UAE',
  'seo.collectionsTitle': 'Collections',
  'seo.collectionsDesc': 'Olive trees, palms, agaves, cacti, ornamental and indoor specimens imported from Italy to the UAE.',
  'col.familiesLede': '{n} families of Italian-grown stock, selected for UAE conditions.',
  // Like ftr.allEmirates: English spells the number, Arabic and Italian
  // inflect it with the noun, so the Arabic drops the token rather than
  // wedging a digit into a phrase that will not take one.
  'col.allEmirates': 'All {n} emirates',
  'col.weeks': '{min}–{max} weeks',
  'seo.collectionDesc': '{blurb} {count} supplied and delivered across the United Arab Emirates. Price on request.',
  'cat.pot': 'Pot',
  'cat.diameter': 'Diameter',

  // ── specimen page ──
  'det.breadcrumb': 'Breadcrumb',
  'det.request': 'Request this specimen',
  'det.bulk': 'Bulk pricing',
  'det.reference': 'Reference {ref}',
  'det.availability': 'Availability',
  'det.price': 'Price',
  'det.onRequest': 'On request',
  'det.photoNote': 'Catalogue photograph under review — it may not represent this specimen. Current photographs are supplied with the quotation.',
  'det.livingStock': 'Living stock: dimensions are indicative and vary between individual specimens. Final size, form and price are confirmed on the quotation. Typical lead time {min}–{max} weeks from order confirmation to delivery on site.',
  'det.more': 'More from {family}',

  // ── catalogue, collections, journal ──
  'cat.noMatch': 'Nothing in the catalogue matches',
  'cat.askSource': 'Ask us to source it',
  'cat.matching': 'matching',
  'col.see': 'See the collection',
  'col.others': 'The other collections',
  'col.othersAria': 'Other collections',
  'jrn.likeThis': 'Looking for a specimen like this?',
  'jrn.more': 'More from the journal',

  // ── coverage ──
  'loc.eyebrow': 'Coverage',
  'loc.title': 'Tree supply & delivery in {name}',
  'loc.onSite': 'What that means on site',
  'loc.common': 'Commonly specified here',
  'loc.requestPricing': 'Request pricing for {name}',
  'loc.alsoDelivering': 'Also delivering to',
  'loc.otherEmirates': 'Other emirates',

  // ── forms and the page that is not there ──
  'qf.error': 'Something went wrong.',
  'qf.consentA': 'I agree that',
  'qf.consentB': 'may store these details and contact me about this enquiry. We do not sell or share your data.',
  'qf.sending': 'Sending…',
  'qf.send': 'Send enquiry',
  'sl.neededBy': 'Needed by',
  'sl.optional': 'optional',
  'sl.company': 'Company',
  'sl.plantsTotal': '{n} plants in total',
  'sl.clear': 'Clear the list',
  'quote.validFor': 'Valid {days} days, with specification and lead time.',
  'quote.leadNote': 'Typical lead time is {min}–{max} weeks from order confirmation to delivery on a UAE site. Large or out-of-season specimens can take longer — we will tell you honestly rather than promise a date we cannot hold.',
  'svc.leadTimeA': 'Typical lead time is',
  'svc.leadTimeWeeks': '{min}–{max} weeks',
  'svc.leadTimeB': 'from order confirmation to site delivery — selection, documentation, sailing and acclimatisation included.',
  // ── when a page fails rather than being missing ──
  'error.eyebrow': 'SOMETHING WENT WRONG',
  'error.title': 'This page did not load.',
  'error.lede': 'The fault is ours, not yours, and it has been recorded. Try again — most of these clear on a second attempt — or go back to the front page and carry on from there.',
  'error.retry': 'Try again',
  'error.home': 'Back to the front page',
  'error.reference': 'Reference',
  'nf.title': 'That page has been replanted.',
  'nf.lede': 'The page you asked for is not here. The catalogue is.',
  'nf.browse': 'Browse the catalogue',
  'map.uae': 'UNITED ARAB EMIRATES',
  'map.allEmirates': 'all seven emirates',
  'map.italy': 'ITALY',
  'map.tunis': 'Tunis',
  'map.suez': 'Suez',
  'map.hormuz': 'Strait of Hormuz',
  'map.alt': 'Three routes from Italian nurseries to the United Arab Emirates: by sea through Suez and the Strait of Hormuz, by air over Anatolia and the Gulf, and overland by way of Tunis and the North African coast.',
  'map.bySea': 'By sea',
  'map.byAir': 'By air',
  'map.overland': 'Overland',

  // ── language ──
  'proof.specimens': 'specimens catalogued',
  'proof.regions': 'Italian growing regions',
  'proof.emirates': 'emirates covered',
  'proof.weeks': 'weeks, order to site',
  'brand.line': 'Italian roots\nfor a greener tomorrow',

  'lang.label': 'Language',
} as const;

export type UIKey = keyof typeof en;

/** Arabic, as a UAE buyer reads it rather than as a dictionary renders it. */
const ar: Record<UIKey, string> = {
  'nav.catalog': 'الكتالوج',
  'nav.collections': 'المجموعات',
  'nav.services': 'الخدمات',
  'nav.journal': 'المدوّنة',
  'nav.about': 'من نحن',
  'nav.contact': 'تواصل معنا',
  'nav.main': 'الرئيسية',
  'nav.menu': 'القائمة',
  'nav.open': 'افتح القائمة',
  'nav.closeMenu': 'أغلق القائمة',
  'nav.close': 'إغلاق',
  'nav.skip': 'تخطَّ إلى المحتوى',

  'cta.quote': 'اطلب عرض سعر',
  'cta.quote.short': 'عرض سعر',
  'cta.bulk': 'أسعار الجملة والمشاريع',
  'cta.sourcing': 'ابحث لي عن شجرة بعينها',
  'cta.viewAll': 'تصفّح الكتالوج كاملًا',

  'ftr.catalogue': 'الكتالوج',
  'ftr.company': 'الشركة',
  'ftr.enquiries': 'الاستفسارات',
  'ftr.aboutUs': 'من نحن',
  'ftr.legal': 'الشؤون القانونية',
  'ftr.allSpecimens': 'جميع الأصناف ({n})',
  'ftr.deliveringTo': 'نوصّل إلى',
  'ftr.sourcedFrom': 'المصدر',
  'ftr.leadTime': 'مدة التوريد',
  'ftr.weeksToSite': 'من {min} إلى {max} أسابيع حتى الموقع',
  'ftr.allEmirates': 'جميع الإمارات',
  'ftr.rights': 'جميع الأسعار عند الطلب.',
  'ftr.vat': 'الأسعار غير شاملة ضريبة القيمة المضافة حيثما تنطبق. المواصفات استرشادية؛ والأشجار كائنات حيّة تتفاوت في الحجم والشكل.',
  'ftr.licence': 'رخصة تجارية رقم {n}',
  'ftr.trn': 'الرقم الضريبي {n}',

  'legal.privacy': 'الخصوصية',
  'legal.terms': 'شروط الاستخدام',
  'legal.termsOfSale': 'شروط البيع',
  'legal.refunds': 'الاستبدال والاسترجاع',
  'legal.disclaimer': 'إخلاء المسؤولية',
  'legal.onThisPage': 'في هذه الصفحة',
  'legal.updated': 'آخر تحديث {date}',
  'legal.email': 'البريد الإلكتروني:',
  'legal.telephone': 'الهاتف:',
  'legal.enquiryForm': 'نموذج الاستفسار',
  'legal.eyebrow': 'القانونية',
  'legal.indexTitle': 'الصفحات القانونية',
  'legal.indexDescription': 'سياسة الخصوصية، وشروط الاستخدام، وشروط البيع، والاستبدال والاسترجاع، وإخلاء المسؤولية لموقع «فيردي غاردن للتجارة».',
  'legal.alsoOnThisSite': 'أيضًا على هذا الموقع:',
  'legal.registeredIn': 'مسجّلة في {city}، {country}.',
  'legal.licence': 'الرخصة التجارية:',
  'legal.trn': 'رقم التسجيل الضريبي:',
  'legal.whatsapp': 'واتساب:',
  'legal.noChannelsA': 'رقم الهاتف وصندوق البريد المُعلنان يبدأان العمل مع إطلاق نطاق الشركة. وإلى أن يحدث ذلك، فإن',
  'legal.noChannelsB': 'هو الطريق للوصول إلينا، وكل استفسار يُرسل عبره يُقرأ — بما في ذلك استفسار عن هذه الوثيقة. نفضّل أن نقول لك ذلك على أن ننشر عنوانًا لا يرد عليه أحد.',
  'legal.vatCharged': 'الأسعار لا تشمل ضريبة القيمة المضافة، وتُضاف بنسبة {rate}% حيث تنطبق.',
  'legal.vatNotRegistered': 'الأسعار لا تشمل ضريبة القيمة المضافة. لسنا مسجلين حاليًا في ضريبة القيمة المضافة، فلا تُحتسب ولا تُعرض — والمورّد غير المسجّل لا يجوز له احتسابها.',
  'legal.prevails': 'هذه الصفحة ترجمة مقدَّمة للتيسير على القارئ. وفي حال وجود أي اختلاف، يُعتدّ بالنسخة الإنجليزية.',

  'cat.sortReference': 'الرقم المرجعي',
  'cat.sortTallest': 'الأطول أولاً',
  'cat.sortSmallest': 'الأقصر أولاً',
  'svc.s1.t': 'الاختيار في المشتل',
  'svc.s1.b': 'نختار النبتة بعينها في المشتل، في توسكانا أو بوليا أو صقلية أو لومبارديا — وفق مواصفتك، لا مما تصادف أن تحمله قائمة مخزون ذلك الشهر.',
  'svc.s1.d': 'صور للشجرة نفسها قبل الالتزام بأي شيء.',
  'svc.s2.t': 'الاستيراد والمستندات',
  'svc.s2.b': 'الشهادات الصحّية النباتية وتصاريح الاستيراد والتخليص الجمركي والأوراق التي تستلزمها المواد النباتية الحيّة في الطرفين.',
  'svc.s2.d': 'نتولّاها نحن. لا شيء في هذه القائمة يصبح مشكلتك عند الحدود.',
  'svc.s3.t': 'التأقلم',
  'svc.s3.b': 'تهيئة عند الوصول قبل الإفراج عن المخزون إلى الموقع، حتى تلتقي شجرة خرجت للتوّ من شتاء إيطالي بصيف الخليج على مراحل.',
  'svc.s3.d': 'هذه الخطوة هي التي تقرّر إن كانت الشجرة ستترسّخ أم تفشل في عامها الأول.',
  'svc.s4.t': 'النقل والتفريغ',
  'svc.s4.b': 'مقطورة منخفضة، وونش أو رافعة هيدروليكية حين تتطلّب الكتلة الجذرية ذلك. ويُتأكَّد من الوصول إلى الموقع — عرض البوّابات والأسلاك العلوية وتحمّل الأرض — قبل الاتفاق على موعد التسليم.',
  'svc.s4.d': 'اختياري. كثير من المقاولين يأخذون التوريد وحده، وهو مسعّر أيضاً.',
  'svc.s5.t': 'الغرس',
  'svc.s5.b': 'تجهيز الحفرة وتحسين التربة والتدعيم وتوصيل الريّ، حين يكون الغرس ضمن النطاق المسعّر.',
  'svc.s5.d': 'للمشاريع التي تمتدّ شهوراً لا تسليمة واحدة.',
  'svc.s6.t': 'توريد المشاريع',
  'svc.s6.b': 'شحنات مرحلية محكومة بمواصفة واحدة عبر المشروع، حتى تطابق أشجار المرحلة الرابعة أشجار المرحلة الأولى.',
  'svc.s6.d': 'مواصفة واحدة، تبقى سارية طوال عمر المشروع.',
  'qf.type.quote': 'تسعير شجرة بعينها',
  'qf.type.quote.hint': 'تعرف ما تريده',
  'qf.type.bulk': 'تسعير كميات / مشاريع',
  'qf.type.bulk.hint': 'كميات لمشروع',
  'qf.type.sourcing': 'البحث عن شجرة محدّدة',
  'qf.type.sourcing.hint': 'غير موجودة في الكتالوج',
  'qf.msg.sourcing': 'صف الشجرة التي تبحث عنها — الصنف والعمر والارتفاع ومحيط الجذع والشكل',
  'qf.msg.general': 'أي شيء آخر ينبغي أن نعرفه — الوصول إلى الموقع، الغرس، الجدول الزمني',
  'Add to your shortlist': 'أضف هذا النموذج إلى قائمتك',
  'Remove from your shortlist': 'أزل هذا النموذج من قائمتك',
  'qf.contact.whatsapp': 'أرسلها إلينا على واتساب بدلاً من ذلك: {n}',
  'qf.contact.email': 'أرسلها إلينا بالبريد بدلاً من ذلك: {n}',
  'qf.contact.retry': 'من فضلك حاول بعد قليل.',
  'qf.err.tooLong': 'هذا أطول ممّا يقبله النموذج. اختصره ثم أرسله مرّة أخرى.',
  'qf.err.name': 'من فضلك اكتب اسماً نردّ عليه.',
  'qf.err.email': 'عنوان البريد لا يبدو صحيحاً. تحقّق منه ثم أرسله مرّة أخرى.',
  'qf.err.quantity': 'الكمية يجب أن تكون عدداً صحيحاً واحداً فأكثر.',
  'qf.err.consent': 'من فضلك علّم على المربّع حتى نتمكّن من الردّ عليك.',
  'qf.err.generic': 'لم يُقبل شيء في النموذج. راجع الحقول ثم أرسله مرّة أخرى.',
  'qf.err.rateLimit': 'هذه عدّة استفسارات في وقت قصير. انتظر دقيقة ثم حاول مجدّداً.',
  'qf.err.notRecorded': 'لم يُسجَّل استفسارك.',
  'cat.height': 'الارتفاع',
  'cat.addToList': 'أضف إلى القائمة',
  'cat.onList': 'في قائمتك',
  'cat.shortlist': 'قائمتك',
  'cat.newPhoto': 'صورة جديدة قريبًا',
  'cat.priceOnRequest': 'السعر عند الطلب',
  'seo.catalogTitle': 'الكتالوج — أشجار ونباتات إيطالية للإمارات',
  'seo.catalogDesc': 'تصفّح أشجار الزيتون المميّزة والنخيل والأغاف والصبّار والأشجار الزينية المستوردة من إيطاليا والمورّدة في جميع أنحاء الإمارات العربية المتحدة. جميع الأسعار عند الطلب.',
  'seo.servicesTitle': 'الخدمات — التوريد والاستيراد والتسليم والغرس',
  'seo.servicesDesc': 'توريد الأشجار من المشاتل الإيطالية، والاستيراد والأوراق الصحّية النباتية، والتأقلم، والتسليم مع التفريغ بالونش، والغرس في جميع أنحاء الإمارات.',
  'seo.aboutTitle': 'من نحن',
  'seo.aboutDesc': 'تستورد فيردي غاردن للتجارة أشجاراً ونباتات فاخرة من المشاتل الإيطالية وتورّدها لمقاولي تنسيق الحدائق والمطوّرين والفنادق والمزارع الخاصة في جميع أنحاء الإمارات.',
  'seo.contactTitle': 'تواصل معنا',
  'seo.contactDesc': 'تواصل مع فيردي غاردن للتجارة — واتساب وهاتف وبريد، تسليم في جميع أنحاء الإمارات، وما الذي ترسله إلينا ليعود إليك عرض السعر في اليوم نفسه.',
  'seo.quoteTitle': 'اطلب عرض سعر',
  'seo.quoteDesc': 'أخبرنا بالأصناف والمقاسات والكميات والموقع. نعود إليك بالتوافر ومدّة التوريد وعرض سعر مسعّر للتسليم في أي مكان في الإمارات.',
  'seo.locationTitle': 'توريد وتسليم الأشجار الإيطالية في {name}',
  'seo.locationDesc': '{intro} أشجار زيتون مميّزة ونخيل ونباتات زينية مستوردة من إيطاليا وتُسلّم في {name}.',
  'seo.specimenTitle': '{name}{size} — مستوردة من إيطاليا',
  'seo.specimenDesc': '{desc} الرقم المرجعي {ref}. تُورّد وتُسلّم في جميع أنحاء الإمارات. السعر عند الطلب.',
  'seo.collectionTitle': '{name} مستوردة من إيطاليا إلى الإمارات',
  'seo.collectionsTitle': 'المجموعات',
  'seo.collectionsDesc': 'أشجار زيتون ونخيل وأغاف وصبّار ونباتات زينة وداخلية، مستوردة من إيطاليا إلى الإمارات.',
  'col.familiesLede': '{n} مجموعات من المشتل الإيطالي، مُنتقاة لظروف الإمارات.',
  'col.allEmirates': 'الإمارات السبع جميعها',
  'col.weeks': 'من {min} إلى {max} أسبوعًا',
  'seo.collectionDesc': '{blurb} {count} تُورّد وتُسلّم في جميع أنحاء دولة الإمارات العربية المتحدة. السعر عند الطلب.',
  'cat.pot': 'الأصيص',
  'cat.diameter': 'القطر',

  'det.breadcrumb': 'مسار التصفّح',
  'det.request': 'اطلب هذه الشجرة',
  'det.bulk': 'أسعار الجملة',
  'det.reference': 'الرقم المرجعي {ref}',
  'det.availability': 'التوفّر',
  'det.price': 'السعر',
  'det.onRequest': 'عند الطلب',
  'det.photoNote': 'صورة الكتالوج قيد المراجعة — وقد لا تمثّل هذه الشجرة بعينها. وتُقدّم الصور الحالية مع عرض السعر.',
  'det.livingStock': 'بضاعة حيّة: الأبعاد استرشادية وتختلف من شجرة إلى أخرى. ويُؤكّد الحجم والشكل والسعر النهائي في عرض السعر. المهلة المعتادة {min}–{max} أسبوعًا من تأكيد الطلب إلى التسليم في الموقع.',
  'det.more': 'المزيد من {family}',

  'cat.noMatch': 'لا شيء في الكتالوج يطابق',
  'cat.askSource': 'اطلب منّا توفيرها',
  'cat.matching': 'مطابق لـ',
  'col.see': 'تصفّح المجموعة',
  'col.others': 'المجموعات الأخرى',
  'col.othersAria': 'مجموعات أخرى',
  'jrn.likeThis': 'تبحث عن شجرة مثل هذه؟',
  'jrn.more': 'المزيد من المدوّنة',

  'loc.eyebrow': 'نطاق التغطية',
  'loc.title': 'توريد الأشجار وتسليمها في {name}',
  'loc.onSite': 'ما يعنيه ذلك في الموقع',
  'loc.common': 'الأكثر طلبًا هنا',
  'loc.requestPricing': 'اطلب تسعيرًا لـ{name}',
  'loc.alsoDelivering': 'نسلّم أيضًا إلى',
  'loc.otherEmirates': 'إمارات أخرى',

  'qf.error': 'حدث خطأ ما.',
  'qf.consentA': 'أوافق على أن تحتفظ',
  'qf.consentB': 'بهذه البيانات وأن تتواصل معي بشأن هذا الاستفسار. ونحن لا نبيع بياناتك ولا نشاركها.',
  'qf.sending': 'جارٍ الإرسال…',
  'qf.send': 'أرسل الاستفسار',
  'sl.neededBy': 'مطلوبة بحلول',
  'sl.optional': 'اختياري',
  'sl.company': 'الشركة',
  'sl.plantsTotal': '{n} نبتة إجمالًا',
  'sl.clear': 'امسح القائمة',
  'quote.validFor': 'صالح {days} يومًا، مع المواصفة ومهلة التنفيذ.',
  'quote.leadNote': 'المهلة المعتادة {min}–{max} أسبوعًا من تأكيد الطلب إلى التسليم في موقع داخل الإمارات. وقد تطول مع الأشجار الكبيرة أو خارج الموسم — وسنقول لك ذلك بصراحة بدل أن نعد بتاريخ لا نقدر عليه.',
  'svc.leadTimeA': 'المهلة المعتادة',
  'svc.leadTimeWeeks': '{min}–{max} أسبوعًا',
  'svc.leadTimeB': 'من تأكيد الطلب إلى التسليم في الموقع — شاملة الانتقاء والمستندات والإبحار والتأقلم.',
  'error.eyebrow': 'حدث خطأ ما',
  'error.title': 'تعذّر تحميل هذه الصفحة.',
  'error.lede': 'الخطأ من عندنا لا من عندك، وقد سُجّل. أعد المحاولة — فأغلب هذه الأعطال تزول من المرة الثانية — أو عد إلى الصفحة الرئيسية وتابع من هناك.',
  'error.retry': 'أعد المحاولة',
  'error.home': 'العودة إلى الصفحة الرئيسية',
  'error.reference': 'الرقم المرجعي',
  'nf.title': 'هذه الصفحة نُقلت إلى موضع آخر.',
  'nf.lede': 'الصفحة التي طلبتها ليست هنا. أمّا الكتالوج فهو هنا.',
  'nf.browse': 'تصفّح الكتالوج',
  'map.uae': 'الإمارات العربية المتحدة',
  'map.allEmirates': 'الإمارات السبع جميعها',
  'map.italy': 'إيطاليا',
  'map.tunis': 'تونس',
  'map.suez': 'السويس',
  'map.hormuz': 'مضيق هرمز',
  'map.alt': 'ثلاثة مسارات من المشاتل الإيطالية إلى الإمارات العربية المتحدة: بحراً عبر السويس ومضيق هرمز، وجواً فوق الأناضول والخليج، وبراً عبر تونس وساحل شمال أفريقيا.',
  'map.bySea': 'بحراً',
  'map.byAir': 'جواً',
  'map.overland': 'براً',

  'proof.specimens': 'صنفًا في الكتالوج',
  'proof.regions': 'مناطق إنتاج إيطالية',
  'proof.emirates': 'إمارات نغطّيها',
  'proof.weeks': 'أسابيع من الطلب إلى الموقع',
  'brand.line': 'جذورٌ إيطالية\nلغدٍ أكثر خضرة',

  'lang.label': 'اللغة',
};

/** Italian, for the growers and for the half of this brand that is Italian. */
const it: Record<UIKey, string> = {
  'nav.catalog': 'Catalogo',
  'nav.collections': 'Collezioni',
  'nav.services': 'Servizi',
  'nav.journal': 'Giornale',
  'nav.about': 'Chi siamo',
  'nav.contact': 'Contatti',
  'nav.main': 'Principale',
  'nav.menu': 'Menu',
  'nav.open': 'Apri il menu',
  'nav.closeMenu': 'Chiudi il menu',
  'nav.close': 'Chiudi',
  'nav.skip': 'Vai al contenuto',

  'cta.quote': 'Richiedi un preventivo',
  'cta.quote.short': 'Preventivo',
  'cta.bulk': 'Prezzi per volumi e progetti',
  'cta.sourcing': 'Cerca un esemplare specifico',
  'cta.viewAll': 'Sfoglia tutto il catalogo',

  'ftr.catalogue': 'Catalogo',
  'ftr.company': 'Azienda',
  'ftr.enquiries': 'Richieste',
  'ftr.aboutUs': 'Chi siamo',
  'ftr.legal': 'Note legali',
  'ftr.allSpecimens': 'Tutti i {n} esemplari',
  'ftr.deliveringTo': 'Consegniamo in',
  'ftr.sourcedFrom': 'Provenienza',
  'ftr.leadTime': 'Tempi di consegna',
  'ftr.weeksToSite': '{min}–{max} settimane in cantiere',
  'ftr.allEmirates': 'Tutti gli Emirati',
  'ftr.rights': 'Tutti i prezzi su richiesta.',
  'ftr.vat': 'Prezzi IVA esclusa ove applicabile. Le specifiche sono indicative; essendo piante vive, dimensioni e portamento variano.',
  'ftr.licence': 'Licenza commerciale {n}',
  'ftr.trn': 'Partita IVA (TRN) {n}',

  'legal.privacy': 'Privacy',
  'legal.terms': 'Termini di utilizzo',
  'legal.termsOfSale': 'Condizioni di vendita',
  'legal.refunds': 'Sostituzioni e rimborsi',
  'legal.disclaimer': 'Esclusione di responsabilità',
  'legal.onThisPage': 'In questa pagina',
  'legal.updated': 'Ultimo aggiornamento {date}',
  'legal.email': 'E-mail:',
  'legal.telephone': 'Telefono:',
  'legal.enquiryForm': 'modulo di richiesta',
  'legal.eyebrow': 'Note legali',
  'legal.indexTitle': 'Note legali',
  'legal.indexDescription': 'Informativa sulla privacy, termini di utilizzo, condizioni di vendita, sostituzioni e rimborsi ed esclusione di responsabilità di Verde Garden Trading.',
  'legal.alsoOnThisSite': 'Anche su questo sito:',
  'legal.registeredIn': 'registrata a {city}, {country}.',
  'legal.licence': 'Licenza commerciale:',
  'legal.trn': 'Numero di registrazione fiscale:',
  'legal.whatsapp': 'WhatsApp:',
  'legal.noChannelsA': 'Il nostro numero di telefono e la casella di posta pubblicati entreranno in funzione con il dominio aziendale. Fino ad allora, il',
  'legal.noChannelsB': 'è il modo per raggiungerci, e ogni richiesta inviata da lì viene letta — compresa una richiesta su questo documento. Preferiamo dirvelo piuttosto che pubblicare un recapito a cui nessuno risponde.',
  'legal.vatCharged': 'I prezzi sono al netto dell’IVA, che viene aggiunta al {rate}% dove applicabile.',
  'legal.vatNotRegistered': 'I prezzi sono al netto dell’IVA. Attualmente non siamo registrati ai fini IVA, quindi nessuna IVA viene addebitata né indicata — un fornitore non registrato non può addebitarla.',
  'legal.prevails': 'Questa pagina è una traduzione fornita per comodità di lettura. In caso di discrepanza, prevale la versione inglese.',

  'cat.sortReference': 'Riferimento',
  'cat.sortTallest': 'Prima i più alti',
  'cat.sortSmallest': 'Prima i più bassi',
  'svc.s1.t': 'Selezione in vivaio',
  'svc.s1.b': 'Scegliamo la singola pianta in vivaio, in Toscana, Puglia, Sicilia o Lombardia — secondo la sua specifica, non fra ciò che un listino si trova ad avere quel mese.',
  'svc.s1.d': 'Fotografie dell\'esemplare reale prima di qualsiasi impegno.',
  'svc.s2.t': 'Importazione e documentazione',
  'svc.s2.b': 'Certificazione fitosanitaria, permessi di importazione, sdoganamento e tutta la documentazione che il materiale vegetale vivo comporta da entrambe le parti.',
  'svc.s2.d': 'Ce ne occupiamo noi. Nulla di questo elenco diventa un suo problema alla dogana.',
  'svc.s3.t': 'Acclimatazione',
  'svc.s3.b': 'Condizionamento all\'arrivo prima che la pianta vada in cantiere, così che un albero appena uscito da un inverno italiano incontri l\'estate del Golfo per gradi.',
  'svc.s3.d': 'È il passaggio che decide se un esemplare attecchisce o cede nel primo anno.',
  'svc.s4.t': 'Trasporto e scarico',
  'svc.s4.b': 'Pianale ribassato, e gru o autogru quando la zolla lo impone. L\'accesso al cantiere — larghezza dei cancelli, linee aeree, portanza del terreno — si verifica prima di fissare la data di consegna.',
  'svc.s4.d': 'Facoltativo. Molte imprese prendono la sola fornitura, e anche quella è quotata.',
  'svc.s5.t': 'Messa a dimora',
  'svc.s5.b': 'Scavo, ammendamento del terreno, ancoraggio e allaccio dell\'irrigazione, dove la messa a dimora rientra nel preventivo.',
  'svc.s5.d': 'Per interventi che si svolgono su più mesi anziché in una sola consegna.',
  'svc.s6.t': 'Fornitura di progetto',
  'svc.s6.b': 'Spedizioni per fasi tenute a una sola specifica lungo tutto lo sviluppo, così che gli alberi della quarta fase corrispondano a quelli della prima.',
  'svc.s6.d': 'Una sola specifica, tenuta aperta per tutta la durata dell\'intervento.',
  'qf.type.quote': 'Preventivo per un esemplare',
  'qf.type.quote.hint': 'Sa già cosa le serve',
  'qf.type.bulk': 'Prezzi per quantità / progetto',
  'qf.type.bulk.hint': 'Volumi per un progetto',
  'qf.type.sourcing': 'Ricerca di un albero specifico',
  'qf.type.sourcing.hint': 'Non è a catalogo',
  'qf.msg.sourcing': 'Descriva l\'albero che cerca — specie, età, altezza, circonferenza del tronco, forma',
  'qf.msg.general': 'Qualsiasi altra cosa utile — accesso al cantiere, messa a dimora, tempi',
  'Add to your shortlist': 'Aggiungi alla tua lista',
  'Remove from your shortlist': 'Rimuovi dalla tua lista',
  'qf.contact.whatsapp': 'Ce lo invii invece su WhatsApp: {n}',
  'qf.contact.email': 'Ce lo invii invece per e-mail: {n}',
  'qf.contact.retry': 'Riprovi fra un momento.',
  'qf.err.tooLong': 'È più lungo di quanto il modulo accetti. Lo accorci e lo invii di nuovo.',
  'qf.err.name': 'Indichi un nome a cui possiamo rispondere.',
  'qf.err.email': "L'indirizzo e-mail non sembra corretto. Lo controlli e lo invii di nuovo.",
  'qf.err.quantity': 'La quantità dev\'essere un numero intero pari almeno a uno.',
  'qf.err.consent': 'Spunti la casella perché possiamo risponderle.',
  'qf.err.generic': 'Qualcosa nel modulo non è stato accettato. Controlli i campi e lo invii di nuovo.',
  'qf.err.rateLimit': 'Sono diverse richieste in poco tempo. Attenda un minuto e riprovi.',
  'qf.err.notRecorded': 'La sua richiesta non è stata registrata.',
  'cat.height': 'Altezza',
  'cat.addToList': 'Aggiungi alla lista',
  'cat.onList': 'Nella tua lista',
  'cat.shortlist': 'La tua lista',
  'cat.newPhoto': 'Nuova fotografia in arrivo',
  'cat.priceOnRequest': 'Prezzo su richiesta',
  'seo.catalogTitle': 'Catalogo — alberi e piante italiane per gli Emirati',
  'seo.catalogDesc': 'Sfoglia olivi esemplari, palme, agavi, cactus e alberi ornamentali importati dall\'Italia e forniti in tutti gli Emirati Arabi Uniti. Tutti i prezzi su richiesta.',
  'seo.servicesTitle': 'Servizi — fornitura, importazione, consegna e messa a dimora',
  'seo.servicesDesc': 'Fornitura di alberi da vivai italiani, importazione e documentazione fitosanitaria, acclimatazione, consegna con scarico tramite gru e messa a dimora in tutti gli Emirati.',
  'seo.aboutTitle': 'Chi siamo',
  'seo.aboutDesc': 'Verde Garden Trading importa alberi e piante di pregio da vivai italiani e rifornisce imprese di paesaggistica, sviluppatori, alberghi e tenute private in tutti gli Emirati.',
  'seo.contactTitle': 'Contatti',
  'seo.contactDesc': 'Contatta Verde Garden Trading — WhatsApp, telefono ed e-mail, consegna in tutti gli Emirati Arabi Uniti, e cosa inviarci perché il preventivo torni in giornata.',
  'seo.quoteTitle': 'Richiedi un preventivo',
  'seo.quoteDesc': 'Indichi specie, misure, quantità e cantiere. Torniamo con disponibilità, tempi di consegna e un preventivo quotato per la consegna ovunque negli Emirati.',
  'seo.locationTitle': 'Fornitura e consegna di alberi italiani a {name}',
  'seo.locationDesc': '{intro} Olivi esemplari, palme e piante ornamentali importati dall\'Italia e consegnati a {name}.',
  'seo.specimenTitle': '{name}{size} — importato dall’Italia',
  'seo.specimenDesc': '{desc} Riferimento {ref}. Fornito e consegnato in tutti gli Emirati. Prezzo su richiesta.',
  'seo.collectionTitle': '{name} importati dall’Italia negli Emirati',
  'seo.collectionsTitle': 'Collezioni',
  'seo.collectionsDesc': 'Olivi, palme, agavi, cactus, alberi ornamentali ed esemplari da interno importati dall’Italia negli Emirati.',
  'col.familiesLede': '{n} famiglie di materiale coltivato in Italia, selezionate per le condizioni degli Emirati.',
  'col.allEmirates': 'Tutti e {n} gli emirati',
  'col.weeks': '{min}–{max} settimane',
  'seo.collectionDesc': '{blurb} {count} forniti e consegnati in tutti gli Emirati Arabi Uniti. Prezzo su richiesta.',
  'cat.pot': 'Vaso',
  'cat.diameter': 'Diametro',

  'det.breadcrumb': 'Percorso di navigazione',
  'det.request': 'Richiedi questo esemplare',
  'det.bulk': 'Prezzi per quantità',
  'det.reference': 'Riferimento {ref}',
  'det.availability': 'Disponibilità',
  'det.price': 'Prezzo',
  'det.onRequest': 'Su richiesta',
  'det.photoNote': 'Fotografia di catalogo in revisione — potrebbe non rappresentare questo esemplare. Le fotografie aggiornate sono fornite con il preventivo.',
  'det.livingStock': 'Materiale vivo: le dimensioni sono indicative e variano da un esemplare all’altro. Misura, forma e prezzo definitivi sono confermati nel preventivo. Tempo tipico {min}–{max} settimane dalla conferma dell’ordine alla consegna in cantiere.',
  'det.more': 'Altro da {family}',

  'cat.noMatch': 'Nulla nel catalogo corrisponde a',
  'cat.askSource': 'Chiedeteci di reperirlo',
  'cat.matching': 'che corrispondono a',
  'col.see': 'Vedi la collezione',
  'col.others': 'Le altre collezioni',
  'col.othersAria': 'Altre collezioni',
  'jrn.likeThis': 'Cercate un esemplare come questo?',
  'jrn.more': 'Altro dal giornale',

  'loc.eyebrow': 'Copertura',
  'loc.title': 'Fornitura e consegna di alberi a {name}',
  'loc.onSite': 'Che cosa significa in cantiere',
  'loc.common': 'Più richiesti qui',
  'loc.requestPricing': 'Richiedi un preventivo per {name}',
  'loc.alsoDelivering': 'Consegniamo anche a',
  'loc.otherEmirates': 'Altri emirati',

  'qf.error': 'Qualcosa è andato storto.',
  'qf.consentA': 'Acconsento a che',
  'qf.consentB': 'conservi questi dati e mi contatti in merito a questa richiesta. Non vendiamo né condividiamo i vostri dati.',
  'qf.sending': 'Invio in corso…',
  'qf.send': 'Invia la richiesta',
  'sl.neededBy': 'Necessario entro',
  'sl.optional': 'facoltativo',
  'sl.company': 'Azienda',
  'sl.plantsTotal': '{n} piante in totale',
  'sl.clear': 'Svuota la lista',
  'quote.validFor': 'Valido {days} giorni, con specifica e tempi di consegna.',
  'quote.leadNote': 'Il tempo tipico è di {min}–{max} settimane dalla conferma dell’ordine alla consegna in un cantiere negli Emirati. Esemplari grandi o fuori stagione possono richiedere più tempo — ve lo diremo onestamente anziché promettere una data che non possiamo mantenere.',
  'svc.leadTimeA': 'Il tempo tipico è di',
  'svc.leadTimeWeeks': '{min}–{max} settimane',
  'svc.leadTimeB': 'dalla conferma dell’ordine alla consegna in cantiere — selezione, documentazione, navigazione e acclimatazione compresi.',
  'error.eyebrow': 'QUALCOSA È ANDATO STORTO',
  'error.title': 'Questa pagina non si è caricata.',
  'error.lede': 'La colpa è nostra, non vostra, ed è stata registrata. Riprovate — quasi sempre si risolve al secondo tentativo — oppure tornate alla pagina iniziale e proseguite da lì.',
  'error.retry': 'Riprova',
  'error.home': 'Torna alla pagina iniziale',
  'error.reference': 'Riferimento',
  'nf.title': 'Quella pagina è stata ripiantata altrove.',
  'nf.lede': 'La pagina che cercavate non è qui. Il catalogo sì.',
  'nf.browse': 'Sfoglia il catalogo',
  'map.uae': 'EMIRATI ARABI UNITI',
  'map.allEmirates': 'tutti e sette gli emirati',
  'map.italy': 'ITALIA',
  'map.tunis': 'Tunisi',
  'map.suez': 'Suez',
  'map.hormuz': 'Stretto di Hormuz',
  'map.alt': 'Tre rotte dai vivai italiani agli Emirati Arabi Uniti: via mare attraverso Suez e lo Stretto di Hormuz, via aerea sopra l\'Anatolia e il Golfo, e via terra passando per Tunisi e la costa nordafricana.',
  'map.bySea': 'Via mare',
  'map.byAir': 'Via aerea',
  'map.overland': 'Via terra',

  'proof.specimens': 'esemplari a catalogo',
  'proof.regions': 'regioni italiane di produzione',
  'proof.emirates': 'emirati serviti',
  'proof.weeks': 'settimane dall\'ordine al cantiere',
  'brand.line': 'Radici italiane\nper un domani più verde',

  'lang.label': 'Lingua',
};

const DICTS: Record<Locale, Record<UIKey, string>> = { en, ar, it };

/**
 * The translator for one language.
 *
 *   const t = ui(lang);
 *   t('nav.catalog')                      -> 'الكتالوج'
 *   t('ftr.weeksToSite', { min: 4, max: 8 })
 *
 * Tokens are filled the same way content blocks fill them, and an unknown one
 * is left visible rather than blanked — a label reading "{min} weeks" is a
 * bug somebody reports, while a label reading " weeks" is one nobody notices.
 */
/**
 * The translator for one language.
 *
 * It answers two kinds of key, because there are two kinds of string:
 *
 *   A UIKey — 'nav.catalog' — is chrome, and every language has one. Missing
 *   it is a type error (see the note at the top of this file).
 *
 *   A CopyKey is a sentence from a page, keyed by its own English. Missing it
 *   comes back as that English, which is a page that has not been translated
 *   yet rather than a page with a hole in it.
 *
 * Both go through one function so a page needs one translator rather than two,
 * and so a call site does not have to know which kind of string it is holding.
 */
export function ui(locale: Locale = DEFAULT_LOCALE) {
  const dict = DICTS[locale] ?? DICTS[DEFAULT_LOCALE];
  const copy = COPY_DICTS[locale] ?? {};
  return (key: UIKey | CopyKey, tokens?: Record<string, string | number>): string => {
    const s = (dict as Record<string, string>)[key]
      ?? copy[key as CopyKey]
      ?? (en as Record<string, string>)[key]
      // A CopyKey IS its English, so an untranslated sentence renders itself.
      ?? key;
    return tokens
      ? s.replace(/\{(\w+)\}/g, (all, k) => (k in tokens ? String(tokens[k]) : all))
      : s;
  };
}

/** For tests, and for a console screen that wants to show what is covered. */
export const UI_KEYS = Object.keys(en) as UIKey[];
export const UI_DICTS = DICTS;
