import type { MetadataRoute } from 'next';
import { publishedPosts, contentLastModified } from '@/lib/content';
import { getAllProducts, getFamilies } from '@/lib/products';
import { locations } from '@/lib/locations';
import { LOCALES, LOCALE_TAG, DEFAULT_LOCALE, localePath } from '@/lib/i18n';
import { LEGAL_UPDATED } from '@/lib/legal/types';
import { CATALOGUE } from '@/lib/catalogue-version';

const base = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://verdegarden.example';

// Regenerated when an article is published, and on a timer besides — the same
// reasoning as the pages: a build that could not reach the database must not
// leave the sitemap permanently missing the journal.
export const revalidate = 300;

/**
 * One entry per page PER LANGUAGE, each carrying the whole cluster.
 *
 * This used to return a single entry per page: the English URL as the <loc>,
 * with Arabic and Italian hanging off it as hreflang annotations. The comment
 * that stood here argued that three <url> elements would tell a crawler there
 * are three unrelated pages, and that is the misunderstanding worth writing
 * down, because the shape it produced is also the shape Next's own API
 * reference documents, so it looked right twice over.
 *
 * What makes three URLs one page in three languages is not how many <url>
 * elements there are: it is that each of them carries the SAME complete set of
 * alternates, itself included. <loc> is not a claim about how many pages
 * exist, it is the list of addresses being SUBMITTED for crawling — and with
 * one <loc> per cluster we were submitting 95 of this site's 285 URLs and
 * leaving 190 to be found some other way. There is no other way here: the
 * language menu in src/components/LangSwitch.tsx renders its links only after
 * a click, so the served HTML contains no anchor to /ar or /it at all, and an
 * hreflang annotation is a hint about a page a crawler has already found, not
 * a way of finding one. Two thirds of a trilingual site was never submitted.
 *
 * x-default belongs in the cluster too. Every page's <head> already emits one
 * (alternates() in src/lib/i18n.ts) and the sitemap did not, so the same fact
 * was being declared twice, in two places, with two different answers.
 */
function entries(
  path: string,
  rest: Omit<MetadataRoute.Sitemap[number], 'url' | 'alternates'>,
): MetadataRoute.Sitemap {
  const languages = {
    ...Object.fromEntries(LOCALES.map((l) => [LOCALE_TAG[l], `${base}${localePath(l, path)}`])),
    // A reader whose language we do not publish gets English, which is what
    // the canonical and the <head> already say.
    'x-default': `${base}${localePath(DEFAULT_LOCALE, path)}`,
  };
  return LOCALES.map((l) => ({
    url: `${base}${localePath(l, path)}`,
    alternates: { languages },
    ...rest,
  }));
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  /**
   * WHAT `lastModified` IS FOR, and what it was doing instead.
   *
   * Every entry here used to carry `new Date()`. That tells a crawler all
   * ninety-five pages changed today — and again tomorrow, and the day after.
   * Google's own documentation says it ignores lastmod values it judges
   * unreliable, so the field was not merely useless: it was teaching a
   * crawler to disregard the one signal that says which pages are worth
   * re-fetching, on a site whose catalogue genuinely does change.
   *
   * Each kind of page now carries a date somebody can point at:
   *   · editable pages — when the copy or the page metadata changed
   *   · the catalogue — when products.json changed
   *   · the legal pages — the date printed on them
   *   · an article — the day it was published
   *
   * The date is the same in all three languages, which is the truth: the
   * Arabic page changes when the page changes.
   */
  const catalogue = new Date(CATALOGUE.updated);
  const legal = new Date(LEGAL_UPDATED);
  // A database that cannot be reached must not make every page look new. The
  // catalogue's own date is the oldest defensible answer, not today's.
  const edited = (await contentLastModified()) ?? catalogue;
  const staticPages = ['', '/catalog', '/collections', '/services', '/about', '/contact', '/quote', '/journal'];
  // The legal pages are listed too, at a low priority. They are not what anybody
  // is searching for, but a policy that cannot be found is a policy that does
  // not exist — and a missing privacy page is what a reviewer looks for first.
  const legalPages = ['/legal', '/privacy', '/terms', '/terms-of-sale', '/refunds', '/disclaimer'];
  // Articles are in the database, so the sitemap reads them rather than being
  // regenerated by a deploy. A post published today is discoverable today.
  const posts = await publishedPosts();

  // flatMap, because each page is now three URLs. Ninety-five pages, two
  // hundred and eighty-five entries — Google's limit for one sitemap file is
  // fifty thousand, so there is a great deal of room left before this has to
  // be split with generateSitemaps().
  return [
    ...staticPages.flatMap((p) => entries(p || '/', {
      lastModified: edited,
      changeFrequency: 'weekly' as const,
      priority: p === '' ? 1 : 0.8,
    })),
    ...legalPages.flatMap((p) => entries(p, {
      lastModified: legal,
      changeFrequency: 'yearly' as const,
      priority: 0.2,
    })),
    ...getFamilies().flatMap((f) => entries(`/collections/${f.slug}`, {
      lastModified: catalogue, changeFrequency: 'weekly' as const, priority: 0.7,
    })),
    ...locations.flatMap((l) => entries(`/locations/${l.slug}`, {
      lastModified: edited, changeFrequency: 'monthly' as const, priority: 0.6,
    })),
    ...posts.flatMap((p) => entries(`/journal/${p.slug}`, {
      lastModified: p.published_at ? new Date(p.published_at) : edited,
      changeFrequency: 'monthly' as const, priority: 0.5,
    })),
    // Each specimen carries its photograph. A tree is bought on how it looks,
    // and an image sitemap is what puts sixty-eight of them into Google Images
    // — where somebody searching "ancient olive tree Dubai" actually looks.
    //
    // The photograph is attached to all three language entries because it is
    // on all three pages; an image is submitted against the page it appears
    // on, and the Arabic page is not a page without its photograph.
    ...getAllProducts().flatMap((p) => entries(`/catalog/${p.slug}`, {
      lastModified: catalogue, changeFrequency: 'weekly' as const, priority: 0.6,
    }).map((e) => ({ ...e, images: [`${base}/products/${p.image}`] }))),
  ];
}
