import type { MetadataRoute } from 'next';
import { publishedPosts } from '@/lib/content';
import { getAllProducts, getFamilies } from '@/lib/products';
import { locations } from '@/lib/locations';

const base = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://verdegarden.example';

// Regenerated when an article is published, and on a timer besides — the same
// reasoning as the pages: a build that could not reach the database must not
// leave the sitemap permanently missing the journal.
export const revalidate = 300;

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();
  const staticPages = ['', '/catalog', '/collections', '/services', '/about', '/quote', '/journal'];
  // Articles are in the database, so the sitemap reads them rather than being
  // regenerated by a deploy. A post published today is discoverable today.
  const posts = await publishedPosts();

  return [
    ...staticPages.map((p) => ({
      url: `${base}${p}`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: p === '' ? 1 : 0.8,
    })),
    ...getFamilies().map((f) => ({
      url: `${base}/collections/${f.slug}`,
      lastModified: now, changeFrequency: 'weekly' as const, priority: 0.7,
    })),
    ...locations.map((l) => ({
      url: `${base}/locations/${l.slug}`,
      lastModified: now, changeFrequency: 'monthly' as const, priority: 0.6,
    })),
    ...posts.map((p) => ({
      url: `${base}/journal/${p.slug}`,
      lastModified: p.published_at ? new Date(p.published_at) : now,
      changeFrequency: 'monthly' as const, priority: 0.5,
    })),
    ...getAllProducts().map((p) => ({
      url: `${base}/catalog/${p.slug}`,
      lastModified: now, changeFrequency: 'weekly' as const, priority: 0.6,
    })),
  ];
}
