import type { MetadataRoute } from 'next';
import { publishedPosts, contentLastModified } from '@/lib/content';
import { getAllProducts, getFamilies } from '@/lib/products';
import { locations } from '@/lib/locations';
import { LOCALES, LOCALE_TAG, DEFAULT_LOCALE, localePath } from '@/lib/i18n';
import { LEGAL_UPDATED } from '@/lib/legal/types';
import { CATALOGUE } from '@/lib/catalogue-version';

const base = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://verdegarden.example';

// Regenerated when an article is published, and on a timer besides — the same
// reasoning as the pages: a build that could not reach the database must not
// leave the sitemap permanently missing the journal.
export const revalidate = 300;

/**
 * One entry per page, listing that page in all three languages.
 *
 * Not three entries per page. A sitemap that lists /privacy, /ar/privacy and
 * /it/privacy as three unrelated URLs tells a crawler there are three pages;
 * `alternates.languages` on ONE entry tells it there is one page in three
 * languages, which is the thing that is true and the thing that makes the
 * Arabic version show up for an Arabic reader instead of competing with the
 * English one.
 */
function entry(path: string, rest: Omit<MetadataRoute.Sitemap[number], 'url' | 'alternates'>) {
  return {
    url: `${base}${localePath(DEFAULT_LOCALE, path)}`,
    alternates: {
      languages: Object.fromEntries(
        LOCALES.map((l) => [LOCALE_TAG[l], `${base}${localePath(l, path)}`]),
      ),
    },
    ...rest,
  };
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  /**
   * WHAT `lastModified` IS FOR, and what it was doing instead.
   *
   * Every entry here used to carry `new Date()`. That tells a crawler all
   * ninety-five pages changed today — and again tomorrow, and the day after.
   * Google's own documentation says it ignores lastmod values it judges
   * unreliable, so the field was not merely useless: it was teaching a
   * crawler to disregard the one signal that says which pages are worth
   * re-fetching, on a site whose catalogue genuinely does change.
   *
   * Each kind of page now carries a date somebody can point at:
   *   · editable pages — when the copy or the settings behind them changed
   *   · the catalogue — when products.json changed
   *   · the legal pages — the date printed on them
   *   · an article — the day it was published
   */
  const catalogue = new Date(CATALOGUE.updated);
  const legal = new Date(LEGAL_UPDATED);
  // A database that cannot be reached must not make every page look new. The
  // catalogue's own date is the oldest defensible answer, not today's.
  const edited = (await contentLastModified()) ?? catalogue;
  const staticPages = ['', '/catalog', '/collections', '/services', '/about', '/contact', '/quote', '/journal'];
  // The legal pages are listed too, at a low priority. They are not what anybody
  // is searching for, but a policy that cannot be found is a policy that does
  // not exist — and a missing privacy page is what a reviewer looks for first.
  const legalPages = ['/legal', '/privacy', '/terms', '/terms-of-sale', '/refunds', '/disclaimer'];
  // Articles are in the database, so the sitemap reads them rather than being
  // regenerated by a deploy. A post published today is discoverable today.
  const posts = await publishedPosts();

  return [
    ...staticPages.map((p) => entry(p || '/', {
      lastModified: edited,
      changeFrequency: 'weekly' as const,
      priority: p === '' ? 1 : 0.8,
    })),
    ...legalPages.map((p) => entry(p, {
      lastModified: legal,
      changeFrequency: 'yearly' as const,
      priority: 0.2,
    })),
    ...getFamilies().map((f) => entry(`/collections/${f.slug}`, {
      lastModified: catalogue, changeFrequency: 'weekly' as const, priority: 0.7,
    })),
    ...locations.map((l) => entry(`/locations/${l.slug}`, {
      lastModified: edited, changeFrequency: 'monthly' as const, priority: 0.6,
    })),
    ...posts.map((p) => entry(`/journal/${p.slug}`, {
      lastModified: p.published_at ? new Date(p.published_at) : edited,
      changeFrequency: 'monthly' as const, priority: 0.5,
    })),
    // Each specimen carries its photograph. A tree is bought on how it looks,
    // and an image sitemap is what puts sixty-eight of them into Google Images
    // — where somebody searching "ancient olive tree Dubai" actually looks.
    ...getAllProducts().map((p) => ({
      ...entry(`/catalog/${p.slug}`, {
        lastModified: catalogue, changeFrequency: 'weekly' as const, priority: 0.6,
      }),
      images: [`${base}/products/${p.image}`],
    })),
  ];
}
